### ISSUE TITLE
Error TypeError: callback is not a function

### ISSUE THREAD

**Issue by Talento90** [Mockgoose/Mockgoose#1]
Everytime that I run the example in your main page I get the following error:

```
..\node_modules\mongodb-prebuilt\index.js:83
            callback(child.status);
            ^

TypeError: callback is not a function
    at start (...\node_modules\mongodb-prebuilt\index.js:83:13)
    at Object.start_server (...\node_modules\mongodb-prebuilt\index.js:69:16)
    at ...\node_modules\mockgoose\Mockgoose.js:144:42
```

**Code:**

```
Mockgoose(Mongoose).then(() => {
   Mongoose.connect(config.connectionString, (error) => {
      console.log(error);
   });
});
```

**Versions:**
    "mockgoose": "^6.0.6"
    "mongoose": "^4.5.7"
    "mongo": 3.2.8

**PS:** I just want to use in memory for unit testing purpose!

Thanks for your attention!

**Comment by beldenge** [comment]
I'm also experiencing this issue.  I'm having to stick with version 5.4.1 in order keep things working.  I would love to update to the latest version but this is blocking me.

**Comment by winfinit** [comment]
please reopen if there is still an issue with 7.x (there is an api change)
