### ISSUE TITLE
Put somewhere in the documentation that this doesn't work on Windows

### ISSUE THREAD

**Issue by Arrow7000** [Mockgoose/Mockgoose#11]
To save others from wasting several hours of their lives trying to get this to work.

**Comment by t0nyt93** [comment]
But actually though... That's a ridiculous detail to leave out haha. I just took a few years off my life trying to figure out why it wasn't working.

**Comment by winfinit** [comment]
it should work on windows now with version 7.x, please report it if it doesn't, also pull requests are always welcome (even for documentation)
