### ISSUE TITLE
Move mongoose-prebuilt logfiles to another directory

### ISSUE THREAD

**Issue by sjorssnoeren** [Mockgoose/Mockgoose#13]
I would like the possibility to make Mockgoose write logfiles to another directory. They're now flying around my project root and I'd like to have them separated. Is this something that is already possible or something that's suitable for new functionality?

If you'd like, I can have my go at it, if it's non existing feature. But I think it's good to discuss it's semantics in public.

Would love to hear,

**Comment by winfinit** [comment]
@sjorssnoeren with 7.x you shouldn't see any logs flying around, unless you are setting DEBUG=mongo* or something similar to that.

I see that i took a shortcut with 7.x release by not giving mockgoose user to pass their own parameters, so I will fix that soon. I am thinking that you could pass logpath to mongod, however I would need to test and see if that will mess with MongodHelper class that is reading logs from spawned process to determine if process started successfully or not.
