### ISSUE TITLE
npm install mockgoose downloads older version

### ISSUE THREAD

**Issue by bobbarjung** [Mockgoose/Mockgoose#14]
HI,
 I am trying to use mockgoose obtained from npm install - but the code examples documented here (using prepareStorage) does not match the version downloaded via npm install. - Trying the older documentation approach did not work either - With the older approach, I hit a max timeout (2000ms) in my mocha tests when trying to make mongoose calls like create/find.

**Comment by winfinit** [comment]
You will need to increase that timeout, 2000ms is. It enough. Increase it to something like a minute (first run might take even longer, depends on your connection)

**Comment by bobbarjung** [comment]
Thanks @winfinit for your response. I will try using 1 minute timeout (60000ms) I am confused though - I thought mockgoose will stub out the actual mongodb connection and create a in-memory/in local FS DB instead. So I am not sure how my connection matters. Do I still need to provide the connection to a real mongod database for mockgoose to work? I currently don't.

**Comment by winfinit** [comment]
You don't have to provide a connection, mockgoose will replace mongo connection by itself and will download appropriate mongod, spawn a process with in memory storage, and when connect or createConnection method is invoked, mockgoose will assist it

**Comment by winfinit** [comment]
fir my tests I am throwing a mocha.opts file in my test directory with --timeout 60000 that way I don't have to modify any CI tools, etc...

**Comment by bobbarjung** [comment]
@winfinit I tried doing npm install again today and observed that a more recent version was installed. I am now about to call the methods listed in the documentation like mockgoose.prepareStorage and mockgoose.helper.reset(). I also switched to a 60000 ms timeout and everything seems to be working now. Mockgoose is a really powerful tool, and I hope to use it extensively going forward. Thank you
