### ISSUE TITLE
FR - create @types/mockgoose

### ISSUE THREAD

**Issue by qneyrat** [Mockgoose/Mockgoose#16]
Create @types/mockgoose package for compatiblity with typescript https://github.com/DefinitelyTyped/DefinitelyTyped
It's nice for typescript community. Thanks :)

**Comment by winfinit** [comment]
Question for you, is it necessary to do that even tho types key is present in package.json and types are part of release? Because I am actually using this package in a typescript project and VS is resolving typings correctly

**Comment by winfinit** [comment]
So I am reading https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html and it looks like types is all I need, if package supplies its declaration file, and DT is necessary for packages that are not including typings with its release, please let me know if I am missing something

**Comment by dcharbonnier** [comment]
it's ok @winfinit, no need for this
