### ISSUE TITLE
Mockgoose fails if there is no internet

### ISSUE THREAD

**Issue by Christilut** [Mockgoose/Mockgoose#20]
My wifi was a little slow and this caused a timeout on the first test even with `--timeout 12000`. Then without having internet at all I got `Unhandled rejection RequestError: Error: getaddrinfo ENOTFOUND fastdl.mongodb.org fastdl.mongodb.org:443`.

I think tests should still be able to run without internet so this error should be caught.

**Comment by joeyjiron06** [comment]
i have a similar issue. any idea on why this is happening?

i just see this error 
`Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

here's my code

```
const { expect } = require('chai');
const { Mockgoose } = require('mockgoose');
const mongoose = require('mongoose');

const mockgoose = new Mockgoose(mongoose);

const User = require('../../src/models/user');


describe('User Model', () => {
  before((done) => {
    // create a mockdb that stores in memory
    mockgoose.prepareStorage().then(() => {
      mongoose.Promise = global.Promise;
      mongoose.connect('mongodb://localhost/testdb');
      mongoose.connection.on('connected', (err) => {
        done(err);
      });
    });
  });
  
  describe('save', () => {
    it('should return a promise',  () => {
      let promise = new User({username:'what', password:'1234'}).save();
      expect(promise).to.be.instanceOf(global.Promise);
    });
  });
});
```

**Comment by Christilut** [comment]
You aren't calling done() which is the first parameter of the it() call.

Check Chai documentation

**Comment by joeyjiron06** [comment]
the before hook is failing not my test case. done never gets called in the before hook when im offline. just curious on why we need internet connection for this to work? im hoping thats not the case, but if it is, then can you point me in the right direction so i can submit a PR?

**Comment by winfinit** [comment]
internet connectivity is required to get mongodb, what Mockgoose does is downloading latest binary, and starting mongod on the background with temporary memory storage. 

another thing it does, is comparing your current binary version with latest available, and if there is a newer version available, that one will be downloaded, unless version of DB is specified in the constructor.

**Comment by joeyjiron06** [comment]
i see. gotcha. thanks for the clarification. makes sense. is there a way to turn on verbose logging. maybe this could benefit from better logging?

**Comment by winfinit** [comment]
@joeyjiron06 for logging, there are different categories, if you want to see everything just set DEBUG env to * "DEBUG=*" or something like this, "DEBUG=mongodb*"

**Comment by joeyjiron06** [comment]
awesome thanks!

**Comment by supergiulio2000** [comment]
@winfinit is there a way to avoid the download of the mongodb binary? Or at least to avoid a new download at each new version. I often use the pc with my mobile connection which is limited in speed and amount and mockgoose is downloading about 100Mb almost every day.

**Comment by winfinit** [comment]
@supergiulio2000 you can specify desired version of MongoDB, and that way it won't download new one every time.

```javascript
import * as mongoose from 'mongoose';
import {Mockgoose} from 'mockgoose';
 
let mockgoose: Mockgoose = new Mockgoose(mongoose);
mockgoose.helper.setDbVersion("3.2.1");
 
mockgoose.prepareStorage().then(() => {
    mongoose.connect('mongodb://foobar/baz');
    mongoose.connection.on('connected', () => {  
      console.log('db connection is now open');
    }); 
});
```

**Comment by wheller** [comment]
I'm experiencing the same problem and, although setting the specific version seems great for making sure my tests are in sync with my prod environments, I still get "unable to get signature content". And "ENOTFOUND" for fastdl.mongodb.org. 

I hardcoded the version number, ran successfully a couple of times, then disconnected to test. Any other suggestions?

**Comment by winfinit** [comment]
@wheller issue now is that integrity of downloaded package is being verified, and every test it requires internet connection to grab md5 hash of intended binary and compare it against one that was previously downloaded. That download is about 100 octets in size.

I will have to add additional option to skip that verification...

**Comment by wheller** [comment]
An option to skip the verification if the binary exists would be perfect.  It's not about the size of the download for my team, it's about being able to work completely disconnected like in a plane or in a remote location.

**Comment by winfinit** [comment]
@wheller added offline hash verification, so with 7.2.0 you should be able to work completely offline, given that you already have cached archive.
