### ISSUE TITLE
Can't extract geo keys - Working with Mongodb

### ISSUE THREAD

**Issue by ghost** [Mockgoose/Mockgoose#21]
I have a model with a Point geo index like bellow: 

```
const locationSchema = new Schema({
  user: {
    type: Schema.ObjectId,
    ref: 'User',
    required: true
  },
  location: {
    type: {type: String, default: "Point"},
    coordinates: [Number]
  },
}, {
  timestamps: true
});
```

When I try to insert a location object I'm getting the following error ( I know that is an error related to the empty coordinates array). But if I connect to a real Mongodb instance it works fine. 

MongoError: Can't extract geo keys: { _id: ObjectId('58dd78c6d0999ce7dfebb358'), updatedAt: new Date(1490909382260), createdAt: new Date(1490909382260), user: ObjectId('58dd78c6d0999ce7dfebb356'), location: { coordinates: [], type: "Point" }, __v: 0 }  Point must only contain numeric elements

Mockgoose; 6.0.8
Mongoose: 4.4.19
Mongodb: 3.4.2

Any suggestion?

This is the insert statement:

```
let coord = { coordinates: [ 15.5, 14.5 ] }
Location.create({ user, location: coord })
```

**Comment by winfinit** [comment]
@ronaldo-getreveel sorry for a late reply, few suggestions: use mock goose 7.x, and make sure to specify version of DB that you are testing against, because Mockgoose actually standing up real mongod, there is no mocking that is happening around queries, just connections.

**Comment by dev-rish** [comment]
> @ronaldo-getreveel sorry for a late reply, few suggestions: use mock goose 7.x, and make sure to specify version of DB that you are testing against, because Mockgoose actually standing up real mongod, there is no mocking that is happening around queries, just connections.

I too am facing this issue with my small project. I am not providing any geo data(Using postman). For the same request body, on atlas its working fine (simply creating empty) array but in local DB it thows error "Can't extract geo keys:"
Mongoose: 5.9.7
MongoDB: 4.2.3(Atlas and local both)

Not using Mockgoose(Don't know about it yet)

**Comment by LineDrop** [comment]
I've noticed that the coordinates in MongoDB are reversed: [longitude, latitude] instead of [latitude, longitude].  Reverse your coordinates and try to run a geospatial index again.  Hope this helps!
