### ISSUE TITLE
Specify MongoDB Version

### ISSUE THREAD

**Issue by bharley** [Mockgoose/Mockgoose#23]
Is there any way to specify the MongoDB version that gets downloaded? I see that it is grabbing the latest version by default, but our code isn't compatible with >= 3.5. I tried to follow the source code, and there doesn't seem to be an obvious way of passing the desired version through to `mongodb-download`.

**Comment by winfinit** [comment]
@bharley just did another release, there was a bug that was making this not possible.

+ mockgoose@7.1.0

now there is a helper method:

setDbVersion(versionString: string)

```javascript
import * as mongoose from 'mongoose';
import {Mockgoose} from 'mockgoose';

let mockgoose: Mockgoose = new Mockgoose(mongoose);
mockgoose.helper.setDbVersion("3.2.1");

mockgoose.prepareStorage().then(() => {
	mongoose.connect('mongodb://foobar/baz');
	mongoose.connection.on('connected', () => {  
	  console.log('db connection is now open');
	}); 
});
```

**Comment by bharley** [comment]
@winfinit: Worked perfectly; thanks for the quick resolution!
