### ISSUE TITLE
setDbVersion - CDN error

### ISSUE THREAD

**Issue by Unibozu** [Mockgoose/Mockgoose#29]
Hi,
There is an issue when using an older mongodb version - I've tried 3.2.4 and 3.2.1 (from the documentation). CDN returns a 403 error. Not specifying the version works as expected.

Download URI `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-3.2.4.tgz.md5`

error Message

`
unable to get signature content { StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C3436F1B22D38855</RequestId><HostId>2stV1Lfv2uZn2mZAwTnXcUP+SS87+WIv0fnmPYHvx4rvvbDFMIPdtTaNAMu1KE6xPLvOLHFgJMg=</HostId></Error>"
`

**Comment by Unibozu** [comment]
Actually it works by bumping the minor version to `3.2.14` - I guess mongoDB doesn't keep all minor binaries online

**Comment by Unibozu** [comment]
Might be interesting to use this CDN instead: https://www.mongodb.org/dl/linux/

**Comment by winfinit** [comment]
It is already using mongos CDN

**Comment by Unibozu** [comment]
good to know. I was able to confirm that mongo doesn't keep all minor for all architecture. `3.2.1` is only for `ubuntu1202` while `ubuntu1604` starts at `3.2.7`

Obviously, not your fault but, may be worth adding a line about that in the documentation.
