### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by HoraceShmorace** [Mockgoose/Mockgoose#30]
This documentation is a little light.

If this spins up a mock DB, then why do I need a connection string? 

Is this connecting to an existing test DB, in which case is this module simply providing an alternate DB connection? 

Or does this create a test DB on the fly, in which case, how do I seed it with data?

**Comment by jcar787** [comment]
The way it works is that mockgoose intercepts that connection. That's why you need,
mockgoose = new Mockgoose(mongoose)
before mongoose.connect(connectionString)
it basically simulates your current database, so you can continue using the methods save, find, etc from mongoose.

**Comment by Neoflash1979** [comment]
> how do I seed it with data?

That is a good question. What is the best practice to seed data?

**Comment by winfinit** [comment]
just do a regular insert or many inserts in beforeAll.
