### ISSUE TITLE
Needs a way to stop the MongoDB server

### ISSUE THREAD

**Issue by mr-rodgers** [Mockgoose/Mockgoose#33]
I'm using this code:

```javascript
beforeEach(async () => {
    mockgoose = new Mockgoose(mongoose);
    await mockgoose.prepareStorage();
    await mongoose.connect("mongodb://foo/map-test");
    return;
});

afterEach(async () => {
    await mockgoose.helper.reset();
    await mongoose.disconnect();
    return;
});
```
In Jest, once the tests are done, the process never exits. I noticed that the mongoDB instance is still running at this point. I think there needs to be a function to call so the instance can be stopped, and tests can truly clean up after themselves.

**Comment by janstuemmel** [comment]
monkey patched this with the jest option `--forceExit`.
A real solution would be nice

**Comment by janstuemmel** [comment]
monkey patched that with: 
```js
....
module.exports.close = () => {
  const proc = mockgoose.mongodHelper.mongoBin.childProcess;
  require('tree-kill')(proc.pid, 'SIGKILL', err => {
    if(err) console.error(err.message);
  });
}
```
seems to work, after a few seconds jest will exit

**Comment by yxliang01** [comment]
Hi @janstuemmel, Thanks for your workaround. But, if I call `mockgoose.mongodHelper.mongoBin.childProcess.kill('SIGKILL');` in the `afrerAll`, the test will fail... Haven't got time investigate yet.

Thanks

**Comment by janstuemmel** [comment]
@yxliang01 hm, i think the problem that jest never exits is not that mongoose is still running, its more that there are open connection with mongoose, my last setup with this looks like following:

```js
const connections = mongoose.connections;
const childProcess = mockgoose.mongodHelper.mongoBin.childProcess;

// close all connections
async.each(connections, (con, cb) => con.close(cb));

// kill mongod
childProcess.kill();
```

**Comment by yxliang01** [comment]
@janstuemmel  But this shouldn't be the case because in `afterAll()`, it calls `disconnect()`. But, I will try your solution soon. Thanks!

**Comment by joe-fenton** [comment]
Where did you get with this issue? I'm having similar problems

**Comment by danielantelo** [comment]
Any other solutions to this issue? can't get the above working, and jest is not exiting correctly.

My setupTestFrameworkScriptFile is:

```
beforeAll(async (done) => {
  await mockgoose.prepareStorage()
  await mongoose.connect('mongodb://testdb');
  await fixtures();
  server = app.listen(4000, () => {
    global.agent = request.agent(server);
    done();
  });
});

afterAll(async () => {
  await server.close();
  mongoose.connections.forEach(async (con) => {
    await con.close();
  })
  await mockgoose.mongodHelper.mongoBin.childProcess.kill();
  await mongoose.disconnect();
});
```

**Comment by LoneRifle** [comment]
We have #72 open which will stop mongodb through `mongoose.shutdown`, though this is pending changes from its author. This should resolve this issue.
