### ISSUE TITLE
Running basic Mockgoose example results in 234MB download?

### ISSUE THREAD

**Issue by ketanhdoshi** [Mockgoose/Mockgoose#34]
I'm trying out a basic Mockgoose example based on the documentation on the home page. When I run it, for some reason it seems like it is doing a 234MB download. I have to abort it. Please see the output below.
I've also attached the js code for the test I am running. The code for the schema file can be any simple schema and model, makes no difference.
[mockdb.txt](https://github.com/Mockgoose/Mockgoose/files/1065831/mockdb.txt)

C:\mongo>npm test
> lab -c -v -L
Completed: 1.5 % (3.6mb / 234.5mb

**Comment by winfinit** [comment]
It is downloading mongodb, it does it when you run it for the first time, and if you define a version, it will not do it again.

**Comment by ketanhdoshi** [comment]
Is there a way to turn off the download even for the first time?

And why does it need mongodb, doesn't mockgoose have it's own in-memory db?

Ketan.

**Comment by winfinit** [comment]
It needs mongod, one way to turn it off is to point to existing mongod which I don't recommend, and when you are saying own in memory db, mockgoose is utilizing memory db provided by mongo, which ensures that you are testing against same/similar to your runtime environment.

**Comment by mikeyGlitz** [comment]
Why doesn't this execute as part of a pre/postinstall script? I can see where running the tests in a CI sever could be a problem.

**Comment by winfinit** [comment]
It used to, you would need to look through various reported bugs that made me switch from pre/post install scripts.
