### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by victorperin** [Mockgoose/Mockgoose#38]
Right after installing Mockgoose, i saw this error.

```
(node:15713) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
```
Is this deprecation occurring because Mockgoose or it is in my project (I tried to find, but I'm already using `connect()`

**Comment by pgrekovich** [comment]
Did you use ` useMongoClient `?

**Comment by jakecoffman** [comment]
I have the same issue and when I try to use `useMongoClient` the test freezes until it times out.

**Comment by winfinit** [comment]
please provide sample, or do a PR with a test case that demonstrates this failure.

**Comment by jakecoffman** [comment]
The issue I was having with `useMongoClient` causing test freezes was somehow related to `ava` test runner failing to know when the connect was finished. I switched to using callbacks instead of generators and it started working. I do have a new problem though related to this: #44.
