### ISSUE TITLE
Freezes installer when running on a docker container

### ISSUE THREAD

**Issue by victorperin** [Mockgoose/Mockgoose#40]
I'm using mockgoose on my project, but when i try to run it on a container, it stops running when the message `Completed: 100 % (80.5mb / 80.5mbb` appears.

What is happening? And how can I help with this issue?

**Comment by winfinit** [comment]
if you are still experiencing this issue, please provide more info in this issue, maybe a docker image and instructions on how I can duplicate this behavior.

**Comment by victorperin** [comment]
@winfinit I built this image: https://hub.docker.com/r/victorperin/mockgoose-error/
The Dockerfile i built is:
```
FROM node:8.1.2-alpine
RUN apk update && apk add libc6-compat git

RUN mkdir -p /usr/src
WORKDIR /usr/src
RUN git clone https://github.com/Mockgoose/Mockgoose.git

WORKDIR /usr/src/Mockgoose
RUN npm i

CMD [ "npm", "test" ]
```

to run, you need to run these comands:
```
docker pull victorperin/mockgoose-error
docker run victorperin;mockgoose-error
```

The test stop at this point:
![image](https://user-images.githubusercontent.com/5847145/28289582-8819f050-6b19-11e7-90f8-dd8faf0273d6.png)

(Sorry for the lack of information, I got a problem at work and needed to fix as fast as possible. :smile: )
If you need any help, just say, I can provide more information.

**Comment by victorperin** [comment]
PS: this problem makes impossible run mockgoose on any CI based on Docker Images (CircleCI 2.0)
