### ISSUE TITLE
Using Mockgoose in express app integration test

### ISSUE THREAD

**Issue by Neoflash1979** [Mockgoose/Mockgoose#43]
Using mockgoose in a simple unit test is quite straight-forward. However I'm a bit fuzzy as to how one would go about using mockgoose in an acceptance or integration test.

Given a simple express/MongoDB app like the following:

```
/*app.js*/

const express = require('express')
const app = express()
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var greetingSchema = mongoose.Schema({
    greeting: String
});

var Greeting = mongoose.model('Greeting', greetingSchema);

app.get('/', function (req, res) {
  Greeting.find({greeting: 'Hello World!'}, function (err, greeting){
    res.send(greeting);
  });  
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
```
and a simple integration test like this:

```
/*test.js*/

const app = require('app.js');  
const request = require('supertest');

it('sends "Hello World!" on the response body', (done) => {  
  request(app)
      .get('/')
      .expect(200, 'Hello World!', done);
  });
});
```
By using the actual app in the request, we are connecting to the app's database ('mongodb://localhost/test'). How then can one use mockgoose, or any other solution, to mock the MongoDB database and still run an integration test like the one shown above?

I think including such an example in the documentation could be beneficial.

**Comment by btruhand** [comment]
You can use something proxyquire: https://github.com/thlorenz/proxyquire to replace the instance returned from the mongoose instance. I'd reckon something like this will work
`
/*test.js*/
const request = require('supertest');
const mongoose = require('mongoose');
const Mockgoose = require('mockgoose').Mockgoose;
const mockgoose = new Mockgoose(mongoose);
const proxyquire = require('proxyquire');
const app = proxyrequire('./app.js'. { mongoose: proxiedMongoose });
const proxiedMongoose = {
  connect: (db) => {
    before((done) => {
      mockgoose.prepareStorage().then(function() {
         mongoose.connect(db, (err) => {
           done(err);
         });
      });
    });
  }
};

it('sends "Hello World!" on the response body', (done) => {  
  request(app)
    .get('/')
    .expect(200, 'Hello World!', done);
});
`

Something like the above should work, though I didn't test them myself
