### ISSUE TITLE
Mockgoose times out on travis-ci, but not locally

### ISSUE THREAD

**Issue by mrbgit** [Mockgoose/Mockgoose#49]
I'm using mocha and chai to run my tests and I have https://travis-ci.org/ linked to my GitHub repo for continuous integration. I have set the timeout to 120000 and my tests pass locally with no errors, but when they run on travis-ci the before hook exceeds the timeout. I have tried simplifying the tests down to testing for true === true, but the tests still timeout on the before hook. I've also tried a different setup with exactly setup from another project and it as the same result. I also tried to downgrade Mockgoose to an earlier version from the project that is passing, but it still times out in the same way

The error I'm getting from travis-ci is:

>  1) ContentItem Model "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```'use strict';

const mongoose = require('mongoose');
mongoose.Promise = Promise;
const Mockgoose = require('mockgoose').Mockgoose;
const mockgoose = new Mockgoose(mongoose);
const expect = require('chai').expect;

const ContentItem = require('./ContentItem');

describe('ContentItem Model', function() {
  //extend timeout for mockgoose
  this.timeout(120000);

  before(function(done) {

    mockgoose.prepareStorage().then(function() {
      mongoose.connect('mongodb://example.com/TestingDB', function(err) {
        done(err);
      });
    });
  });

  it('should require title', function (done) {
    const testContentItem = new ContentItem({
      description: 'the quick brown fox jumped over the lazy brown dog'
    });

    testContentItem.save((err) => {
      expect(err).to.exist;
      expect(err.message).to.equal('ContentItem validation failed: title: Path `title` is required.');
      done();
    });
  });

  it('should create a ContentItem when title is included title', function (done) {
    const testContentItem = new ContentItem({
      title: 'Gulliver\'s Travels'
    });

    testContentItem.save((err, item) => {
      expect(err).to.not.exist;
      expect(item.title).to.equal(testContentItem.title);
      done();
    });
  });

  it('should create a ContentItem and set the uniqueTitle', function (done) {
    const testContentItem = new ContentItem({
      title: 'Gulliver\'s Travels'
    });

    testContentItem.save((err, item) => {
      expect(err).to.not.exist;
      expect(item.uniqueTitle).to.contain('gulliver-s-travels-');
      expect(item.uniqueTitle.length).to.equal(32);
      done();
    });
  });

  // restoring everything back
  after( (done) => {

    mockgoose.helper.reset().then(() => {
      done();
    });
  });
});
```

And here's the model:
```'use strict';

const mongoose = require('mongoose');

const contentItemSchema = mongoose.Schema({
  author: String,
  content: String,
  description: String,
  image: {
    src: String,
    name: String
  },
  postType: String,
  subtitle: String,
  title: {
    type: String,
    required: true
  },
  uniqueTitleKey: {
    type: String,
    default: Date.now().toString()
  }
});

contentItemSchema.virtual('uniqueTitle').get(function () {
  return `${this.title.toLowerCase().toString().replace(/[^a-z0-9+]+/gi, '-')}-${this.uniqueTitleKey}`;
});

module.exports = mongoose.model('ContentItem', contentItemSchema);
```

Please let me know if you need more information from me.

Thanks!

**Comment by victorperin** [comment]
This is the same error I have. #48 
The problem is not with Circle CI it self, It seems to happen when using a docker container (Circle CI 2.0 runs on docker).

I don't know what is happening, but seems to be some kind of dependency witch doesn't trow an error.

**Comment by victorperin** [comment]
We can easly test if it works when updated running those commands:

```
docker pull victorperin/mockgoose-error
docker run victorperin/mockgoose-error
```

**Comment by mrbgit** [comment]
@victorperin I was actually able to fix this issue by adding `this.timeout(120000)` inside of both the `before` and `after` blocks and it seems to resolve the issue

**Comment by victorperin** [comment]
Thanks @mrbgit this could help someone with similar issues :)

**Comment by paulbeattie** [comment]
Thanks, this helped me solve this problem. I'm not sure why the downloading of such a large binary (100MB) isn't done as a post install hook. This also messes up the cacheing setup on my CircleCI project as the build step creates a cache of all the modules and this isn't added later as the download happens at runtime :/

**Comment by azdanov** [comment]
Might help someone in the future.
I've tried running tests with jest and mockgoose on Travis and used node v9, which went on in an endless loop.

Same tests executed fine after adjusting the timeout, in my case `jest.setTimeout(12000)`, appending `--maxWorkers 4` max workers flag to jest, and using node v8.

```yml
language: node_js
node_js:
  - "8"
env:
  - DATABASE=mongodb://localhost/my-app
services:
  - mongodb
cache: yarn
script:
  - yarn test --maxWorkers 4
```
