### ISSUE TITLE
[Question] Read data from mockgoose

### ISSUE THREAD

**Issue by chemitaxis** [Mockgoose/Mockgoose#51]
Hi, when I connect to mongodb through Mockgoose, I would like to know if it's possible to read the data from a real database, but when save, update or delete data, make in the memory storage, is this possible? 

In case of not possible, do i need to add the mock data to the memory database? 

Thanks.

**Comment by victorperin** [comment]
I think it's not possible.
When I need to do this kind of test, I do these steps:

- run mockgoose, so all data is fake.
- save some data, inside the test (all data are mocked, so nothing is inserted in a real database).
- verify the test,  (with the data you make)
- reset the database, to make possible to run other tests

This is important, so tests must run without any external factor.

**Comment by chemitaxis** [comment]
Ok perfect thanks ;)
