### ISSUE TITLE
Promise never resolves

### ISSUE THREAD

**Issue by beldenge** [Mockgoose/Mockgoose#6]
Running the following example from the README using version 6.0.8 does not work.

```
var Mongoose = require('mongoose').Mongoose;
var mongoose = new Mongoose();

var mockgoose = require('mockgoose');

before(function(done) {
    mockgoose(mongoose).then(function() {
        mongoose.connect('mongodb://example.com/TestingDB', function(err) {
            done(err);
        });
    });
});

describe('...', function() {
    it("...", function(done) {
        // ...
        done();
    });
});
```

I get the following error, leading me to the conclusion that the promise is not resolving.

> Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

I've tried bumping up the timeout to 60000ms to no avail.

**Comment by TanisTseng** [comment]
I encountered this problem also. It seems to happen on Window 7.
Same code on Mac works fine.

**Comment by jneumann** [comment]
I'm getting the same error message intermittently on OS X. As far as I can tell, the disconnect promise isn't firing properly every time. If I spent some time In the code I could probably put in a PR, but I'm not sure what the best way to debug this would be.

@beldenge Do you have an antivirus running on your computer that could be preventing opening a port?

**Comment by beldenge** [comment]
Hi @jneumann -- Thanks for the suggestion.  I do not see any events in my antivirus when running this test, and I tried running the test with my antivirus disabled to no avail as well.  For what it's worth, I'm using Windows 10, Node 6.7.0, and Mocha 3.1.1.

**Comment by easybird** [comment]
Same issue here for the guys in the team with a Windows computer..

**Comment by markfejes** [comment]
Yeah, same thing stands on Win10 too... on linux it seems to be working. Is this project still maintained?

**Comment by solgarius** [comment]
I just ran into the same problem. It looks like the issue is with the underlying mongodb-prebuilt package. It does not work with windows because it relies on the --fork flag which is linux/os x only. 

See
[winfinit/mongodb-prebuilt#26](https://github.com/winfinit/mongodb-prebuilt/issues/26)
[winfinit/mongodb-prebuilt#29](https://github.com/winfinit/mongodb-prebuilt/issues/29)

So until that changes, I don't know of a way to get mockgoose/mongodb-prebuilt to work on windows.

**Comment by Arrow7000** [comment]
I just spent two hours trying to get Mockgoose to work on my computer. 

If this module doesn't work on the vast majority of computers then please make sure this is stated in the documentation before people end up wasting hours on something that doesn't work.

**Comment by bamse16** [comment]
In my case, the error was caused by requiring the models after the connection was established. Moving `require("models");` after `var mockgoose = require('mockgoose');` and before `before` solved the problem

As a side note, before using `mockgoose`, make sure your tests run fine using a test db.

**Comment by winfinit** [comment]
there was a new rewrite, please attempt to run your test with 7.x (there is API change), and reopen this ticket if there is still an issue

**Comment by TylerSustare** [comment]
This issue is still happening for me. I'm trying to just wrap my main connection in mockgoose like the documentation states and I'm getting a promise rejection error in getOtherOSVersionString() from mongo-dowload.ts 

const Mongoose = require('mongoose').Mongoose;
const mongoose = new Mongoose();
const Mockgoose = require('mockgoose').Mockgoose;
const mockgoose = new Mockgoose(mongoose);
const models = require('./models');
mockgoose.prepareStorage().then(function () {
  mongoose.connect(config.getDbConnectionString('dev'), {
    useMongoClient: true,
  });
});

**Comment by winfinit** [comment]
please set DEBUG=* environment variable, and paste your output.

**Comment by TylerSustare** [comment]
`$ DEBUG=* node ./bin/www
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::b4e9:4ff:fec7:e5f1', 'fe80::c36c:8fab:7ac8:271b' ] +0ms
  mongodb-prebuilt-MongoDBPrebuilt getHomeDirectory(): /Users/sustare/.mongodb-prebuilt +301ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +19ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 27017 +1ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/' +2ms
  express:router:layer new '/' +0ms
  express:router:route new '/orders' +0ms
  express:router:layer new '/orders' +0ms
  express:router:route get '/orders' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/order' +1ms
  express:router:layer new '/order' +0ms
  express:router:route post '/order' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/order' +1ms
  express:router:layer new '/order' +0ms
  express:router:route post '/order' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/nonce_token' +3ms
  express:router:layer new '/nonce_token' +0ms
  express:router:route get '/nonce_token' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/request_customized_model' +0ms
  express:router:layer new '/request_customized_model' +0ms
  express:router:route post '/request_customized_model' +1ms
  express:router:layer new '/' +0ms
  express:application set "x-powered-by" to true +1ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: wetag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/sustare/com.CentralCascadeAutomotiveSales.api/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "views" to '/Users/sustare/com.CentralCascadeAutomotiveSales.api/views' +0ms
  express:application set "view engine" to 'hbs' +0ms
  express:router use '/' query +1ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' logger +0ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +11ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +2ms
  express:router:layer new '/' +0ms
  express:router use '/' cookieParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' serveStatic +1ms
  express:router:layer new '/' +0ms
  express:router use '/' router +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:application set "x-powered-by" to true +2ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: wetag] +0ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/sustare/com.CentralCascadeAutomotiveSales.api/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +3ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' cookieParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/acme/api/v45.1' router +0ms
  express:router:layer new '/acme/api/v45.1' +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: wetag] +0ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +1ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/sustare/com.CentralCascadeAutomotiveSales.api/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +0ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' cookieParser +13ms
  express:router:layer new '/' +1ms
  express:router use '/r' router +0ms
  express:router:layer new '/r' +0ms
  express:application set "port" to 3000 +0ms
  com.centralcascadeautomotivesales.api:server Listening on port 3000 +135ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 27017 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::1 +0ms
  portfinder:testPort entered testPort(): trying fe80::1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::1 w/ port 27017 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::1:27017
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::1',
  port: 27017 } +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 27017 +2ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 27017 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::b4e9:4ff:fec7:e5f1 +0ms
  portfinder:testPort entered testPort(): trying fe80::b4e9:4ff:fec7:e5f1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::b4e9:4ff:fec7:e5f1 w/ port 27017 with error EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::b4e9:4ff:fec7:e5f1:27017
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::b4e9:4ff:fec7:e5f1',
  port: 27017 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 27017 +1ms
  portfinder:testPort done w/ testPort(): OK ::1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::c36c:8fab:7ac8:271b +0ms
  portfinder:testPort entered testPort(): trying fe80::c36c:8fab:7ac8:271b port 27017 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::c36c:8fab:7ac8:271b w/ port 27017 with error EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::c36c:8fab:7ac8:271b:27017
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::c36c:8fab:7ac8:271b',
  port: 27017 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +1ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 27017 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 27017 +1ms
  portfinder:testPort done w/ testPort(): OK ::1 port 27017 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 27017 +0ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 27017, 27017, 27017 ] +1ms
  Mockgoose @prepareStorage mongod args, --port,27017,--storageEngine,ephemeralForTest,--dbpath,/var/folders/zt/0vhpjww15sj0g68rp_5vtjsc0000gn/T/mockgoose/1500586787420 +0ms
  mongodb-download-MongoDBDownload createDownloadDir(): /Users/sustare/.mongodb-prebuilt/mongodb-download +5ms
  mongodb-download-MongoDBDownload getDownloadURI (url obj returned with href): https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-latest.tgz +3ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +0ms
  mongodb-download-MongoDBDownload getTempDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz.downloading +1ms
  mongodb-download-MongoDBDownload getHttpOptions { protocol: 'https:',
  hostname: 'fastdl.mongodb.org',
  path: '/osx/mongodb-osx-x86_64-latest.tgz' } +0ms
  mongodb-download-MongoDBDownload createDownloadDir(): true +2ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +0ms
  mongodb-download-MongoDBDownload sending file from cache /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +0ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +1ms
  mongodb-download-MongoDBDownload @getMD5HashFileLocation resolving md5HashLocation: /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz.md5 +0ms
  mongodb-download-MongoDBDownload @getMD5Hash resolving offlineSignature a811facba94753a2eba574f446561b7e +2ms
  mongodb-download-MongoDBDownload isDownloadPresent() md5 match: true +285ms
  mongodb-download-MongoDBDownload download(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +0ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +1ms
  mongodb-download-MongoDBDownload @getMD5HashFileLocation resolving md5HashLocation: /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz.md5 +0ms
  mongodb-download-MongoDBDownload @getMD5Hash resolving offlineSignature a811facba94753a2eba574f446561b7e +0ms
  mongodb-download-MongoDBDownload getExtractLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/a811facba94753a2eba574f446561b7e +1ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +1ms
  mongodb-download-MongoDBDownload @getMD5HashFileLocation resolving md5HashLocation: /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz.md5 +0ms
  mongodb-download-MongoDBDownload @getMD5Hash resolving offlineSignature a811facba94753a2eba574f446561b7e +0ms
  mongodb-download-MongoDBDownload getDownloadLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz +1ms
  mongodb-download-MongoDBDownload @getMD5HashFileLocation resolving md5HashLocation: /Users/sustare/.mongodb-prebuilt/mongodb-download/mongodb-osx-x86_64-latest.tgz.md5 +0ms
  mongodb-download-MongoDBDownload @getMD5Hash resolving offlineSignature a811facba94753a2eba574f446561b7e +0ms
  mongodb-download-MongoDBDownload getExtractLocation(): /Users/sustare/.mongodb-prebuilt/mongodb-download/a811facba94753a2eba574f446561b7e +0ms
  mongodb-download-MongoDBDownload sending file from cache /Users/sustare/.mongodb-prebuilt/mongodb-download/a811facba94753a2eba574f446561b7e +0ms
  mongodb-download-MongoDBDownload isExtractPresent(): true +0ms
  mongodb-prebuilt-MongoDBPrebuilt resolveBinPath(): /Users/sustare/.mongodb-prebuilt/mongodb-download/a811facba94753a2eba574f446561b7e/mongodb-macOS-x86_64-3.5.5-13-g00ee4f5/bin +8ms
  mongodb-prebuilt-MongoBins getCommand(): /Users/sustare/.mongodb-prebuilt/mongodb-download/a811facba94753a2eba574f446561b7e/mongodb-macOS-x86_64-3.5.5-13-g00ee4f5/bin/mongod +1ms
  mongodb-prebuilt-MongoSupervice isWindows(): false +8ms
  mongodb-prebuilt-MongoSupervice runOnLinux() +0ms
  mongodb-prebuilt-MongoSupervice getSuperviseCommand(): /Users/sustare/com.CentralCascadeAutomotiveSales.api/node_modules/mongodb-prebuilt/built/bin/mongo-supervise.js +1ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.925-0700 I CONTROL  [initandlisten] MongoDB starting : pid=513 port=27017 dbpath=/var/folders/zt/0vhpjww15sj0g68rp_5vtjsc0000gn/T/mockgoose/1500586787420 64-bit host=sustares-MacBook-Pro.local
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] db version v3.5.5-13-g00ee4f5
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] git version: 00ee4f5156348477b9dd3f71b747104794f766c0
  mongodb-prebuilt-MongodHelper  +34ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] allocator: system
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] modules: none
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] build environment:
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten]     distarch: x86_64
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten]     target_arch: x86_64
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.926-0700 I CONTROL  [initandlisten] options: { net: { port: 27017 }, storage: { dbPath: "/var/folders/zt/0vhpjww15sj0g68rp_5vtjsc0000gn/T/mockgoose/1500586787420", engine: "ephemeralForTest" } }
  mongodb-prebuilt-MongodHelper  +0ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten]
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.5.5-13-g00ee4f5) of MongoDB.
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] **       Not recommended for production.
  mongodb-prebuilt-MongodHelper  +9ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten]
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten]
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten]
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] ** NOTE: The ephemeralForTest storage engine is for testing only.
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten] **       Do not use in production.
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.936-0700 I CONTROL  [initandlisten]
  mongodb-prebuilt-MongodHelper  +1ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.937-0700 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/var/folders/zt/0vhpjww15sj0g68rp_5vtjsc0000gn/T/mockgoose/1500586787420/diagnostic.data'
  mongodb-prebuilt-MongodHelper  +1ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.938-0700 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
  mongodb-prebuilt-MongodHelper  +0ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.938-0700 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
  mongodb-prebuilt-MongodHelper 2017-07-20T14:39:47.938-0700 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
  mongodb-prebuilt-MongodHelper  +0ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.938-0700 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
  mongodb-prebuilt-MongodHelper  +0ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.938-0700 I NETWORK  [thread1] waiting for connections on port 27017
  mongodb-prebuilt-MongodHelper  +0ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.956-0700 I NETWORK  [thread1] connection accepted from 127.0.0.1:49239 #1 (1 connection now open)
  mongodb-prebuilt-MongodHelper  +24ms
  mongodb-prebuilt-MongodHelper mongod stdout: 2017-07-20T14:39:47.962-0700 I NETWORK  [conn1] received client metadata from 127.0.0.1:49239 conn1: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "16.6.0" }, platform: "Node.js v6.11.0, LE, mongodb-core: 2.1.11" }
  mongodb-prebuilt-MongodHelper  +1ms
Mongoose connected
  mquery find suppliers {} { fields: {} } +11ms
  mquery find customers {} { fields: {} } +2ms`

The   `mquery find suppliers {} { fields: {} } `+11ms` I'm assuming means mockgoose may be trying to work, but when I try any of my tests that were working when my connection was mab.com I never get any response back from my DB which is now wrapped in the `mockgoose.prepareStorage()...` like I mentioned above.

**Comment by winfinit** [comment]
so from above logs, I see that connection is established successfully, do you have maybe raise condition where query is made before connection is done? because I also see that prepare storage promise is being entered, and mongoose connect call is being made:

```
[thread1] connection accepted from 127.0.0.1:49239 #1 (1 connection now open)
```

**Comment by TylerSustare** [comment]
It could be. That connection appears to be my seed method which I'm calling after I verify the connection (I believe). I updated my original comment to show when this was called. 

However when I try to just run npm test I get this.

```
    $ npm test
    > com.project.api@0.0.0 test /Users/user/com.project.api
    > mocha --timeout 120000


  App
    (node:514) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17):     
    Mongod shutting down 
    Mongoose connected
```

**Comment by aguscarlavan** [comment]
Hi,i'm having the same issue, these are my specs: 

-  node version 6.11.4
-  mocha 2.4.5
-  mockgoose 7.3.3 

and using the following code in "before" of a mocha test:
```javascript
const Mongoose = require('mongoose').Mongoose;
const Mockgoose = require('mockgoose').Mockgoose;
const mongoose = new Mongoose();
const mockgoose = new Mockgoose(mongoose);
mockgoose.prepareStorage()
       .then(() => connection.connect("mongodb://localhost/core"))
       .then(_ => {
               const model = require('./models').default;
               return model.create(// object data... );
       })
       .then(_ => done())
       .catch(err => done(err));

```
The connection is established successfully but the "model.create()" promise is not resolved.

With DEBUG environment variable setted, the output only is:

> "Tue, 07 Nov 2017 12:53:59 GMT Mockgoose @prepareStorage mongod args, --port,27018,--storageEngine,ephemeralForTest,--dbpath,/tmp/mockgoose/1510059239017"

**Comment by nik2code** [comment]
I was facing the same issue. You had to set my proxy because mockgoose have to download  "mongodb-prebuilt"

mockgoose.helper.setProxy('http://xxx.yyy.zzz:port');

**Comment by vicky-gonsalves** [comment]
I got the same issue on vm but works on local machine without any issue( windows machine). It was perfectly working 2 days ago on vm (Travis CI and Circle CI) but suddenly started to hang indefinitely.
