### ISSUE TITLE
I can´t use it

### ISSUE THREAD

**Issue by mmunozpatino** [Mockgoose/Mockgoose#66]
everytime that i rum npm test or mocha y have this and the tests doesn´t happend. helps!
![image](https://user-images.githubusercontent.com/23423556/33686135-a47eace6-dab2-11e7-8af6-f889c84b50ed.png)

**Comment by binary1230** [comment]
@mmunozpatino this is a duplicate of #67 , there are some workarounds over there that worked for me to get rid of that.  though after applying them, I ran into #56 , so kinda stuck myself.

**Comment by LoneRifle** [comment]
Duplicate of #64
