### ISSUE TITLE
mocha 4+ doesn't exit when using mockgoose in tests

### ISSUE THREAD

**Issue by deployable** [Mockgoose/Mockgoose#71]
Mocha 4+ changed behaviour to ["no longer force the process to exit once all tests complete"](https://github.com/mochajs/mocha/blob/b7377b380202d2c0d5634dcb89dc50ea69961fb3/CHANGELOG.md#default-behavior).

Mockgoose runs into this behaviour change due to the child process for mongod stopping mocha from exiting.

**Comment by deployable** [comment]
I've submitted a PR to mongodb-prebuilt to add the helper functions to enable this: https://github.com/winfinit/mongodb-prebuilt/pull/49

**Comment by bbruneau** [comment]
+1, any word on this?

**Comment by pgerlach** [comment]
I use this code in my `after()` function in mocha 4+. But it relies on internals of mockgoose, maybe a mockgoose.disconnect() method would be nice ?
```
  after(async function() {
    await mockgoose.helper.reset();
    await mongoose.disconnect();
    mockgoose.mongodHelper.mongoBin.childProcess.kill('SIGTERM');
  });
```

**Comment by j3ko** [comment]
adding the above code works when there is one test file in mocha 5, but when there are 2+ test files (ie. multiple after's) it still seems to hang.  Is there a better workaround for that?

**Comment by gsikorski** [comment]
@j3ko Something like this works for me:
```
// mongomock.js
const mongoose = require('mongoose'),
    Mockgoose = require('mockgoose').Mockgoose,
    mockgoose = new Mockgoose(mongoose);

module.exports = {
    setup: async function setup() {
        await mockgoose.prepareStorage();
        await mongoose.connect('mongodb://test');
    },

    teardown: async function teardown() {
        await mockgoose.helper.reset();
        await mongoose.disconnect();
        let retval = new Promise(resolve => {
            mockgoose.mongodHelper.mongoBin.childProcess.on('exit', resolve);
        });
        mockgoose.mongodHelper.mongoBin.childProcess.kill('SIGTERM');
        return retval;
    }
};
```
Then in your tests you can do:
```
const mongomock = require('mongomock');

    before(async () => {
        await mongomock.setup();
    });
    ...

    after(async () => {
        await mongomock.teardown();
    });
```
