### ISSUE TITLE
Is required to call mongoose.disconnect after tests has finished ?

### ISSUE THREAD

**Issue by maustand** [Mockgoose/Mockgoose#75]
Hi Guys.

It is a short and stupid question but i would like to know if i am doing well..

I am using mocha as test runner and i would like to know if i should call to "mongoose.disconnect" after my test has finished. I ask this because i dont see it in the Mockgoose documentation that it is necessary.

example: 

```
//myHappyTest.test.js

  before((done) => {
    const mockMongo = new Mockgoose(mongoose);

    mockMongo.prepareStorage().then(() => { 
      mongoose.connect('mongodb://baba').then((err) => {
        done();
      });
    });
  });

  after(() => {
    mongoose.disconnect(); // THIS LINE
  });

  it(aaaa',  () =>  {
//....
  });

```

Info: 
- mockgoose v7.3.5
- mocha v3.5.3

Thanks in advance.

**Comment by konsumer** [comment]
I can't even `disconnect` or `connection.close` to work, as you can see [here](https://github.com/konsumer/mongoose-type-url/blob/master/test/mongoose-type-url.js) with either/both my tests hang.

**Comment by MrToph** [comment]
Same issue here. The tests hang. This makes this library pretty much unusable. 😕

**Comment by LoneRifle** [comment]
#72 is open to gracefully shut down MongoDB and hence mockgoose. This library is no longer actively maintained though, so I would encouage people to check out [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server/) instead
