### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by cloakedch** [Mockgoose/Mockgoose#84]
Is this repository abandoned? The last update is some time ago and there is a high security vulnerability in https-proxy-agent.

If so, it should not be considered for new projects.

**Comment by matejthetree** [comment]
looks like

**Comment by Cherviakov** [comment]
Looks like it is abandoned, but what other package out there to make tests with mongoose?

**Comment by compwright** [comment]
I've submitted a PR to fix it, hopefully we can get it merged soon.

FYI I no longer use this in my projects, because many CI services (such as Travis CI and Bitbucket Pipelines) provide mongodb as a service that can be turned on easily, so you can run tests against a _real_ mongodb connection.

**Comment by matejthetree** [comment]
thx for the tip. I used mongodb-memory-server
